
let matchingProps = 
    {
   "image-gallery":{
      "html":"../../assets/modules/hmh.image_gallery/widgets/explib_image_gallery/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/image_gallery_cpl_template_G3_12.json",
      "mappingPath":"../Mapping/image_gallery_mapping_G3_12.json",
      "templateKG":"../cpl-config/image_gallery_cpl_template_GK_2.json",
      "mappingKG":"../Mapping/image_gallery_mapping_GK_2.json",
      "value":"image-gallery",
      "audioMappingpath":'image_gallery_mapping_audio_G3_12',
      "audioTemplatepath":'image_gallery_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/image-gallery/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/image-gallery\/index.html/
   },
   "mcq":{
      "html":{"checkbox":"../../assets/modules/hmh.cpl_mcq_multi/widgets/cpl_mcq_multi/index.html","radio":"../../assets/modules/hmh.mcq_mrq/widgets/explib_mcq_mrq/index.html"},
      "dataVersion":{"checkbox":"","radio":""},
      "templateKG":{"checkbox":"../cpl-config/mcq_image_ms_cpl_template.json","radio":"../cpl-config/mcq_image_ss_cpl_template.json"},
      "mappingKG":{"checkbox":"../Mapping/mcq_image_ms_mapping.json","radio":"../Mapping/mcq_image_ss_mapping.json"},
      "templatePath":{"checkbox":"../cpl-config/mcq_ms_cpl_template_G3_12.json","radio":"../cpl-config/mcq_ss_cpl_template_G3_12.json"},
      "mappingPath":{"checkbox":"../Mapping/mcq_ms_mapping_G3_12.json","radio":"../Mapping/mcq_ss_mapping_G3_12.json"},
      "deciderProp":'inputType',
      "isControlled":true,
      "value":{"checkbox":"mcq","radio":"mcq"},
      "audioMappingpath":{"checkbox":"mcq_ss_mapping_audio_G3_12","radio":"mcq_ms_mapping_audio_G3_12"},
      "audioTemplatepath":{"checkbox":"mcq_ss_cpl_template_G3_12","radio":"mcq_ms_cpl_template_G3_12"},
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/mcq/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/mcq\/index.html/
   },
   "drawing-tool":{
      "html":"../../assets/modules/hmh.drawing_tool/widgets/explib_drawing_tool/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/draw_cpl_template_G3-12.json",
      "mappingPath":"../Mapping/draw_mapping_G3-12.json",
      "templateKG":"../cpl-config/draw_cpl.json",
      "mappingKG":"../Mapping/draw_mapping.json",
      "value":"drawing-tool",
      "audioMappingpath":'drawing-tool_mapping_audio_G3_12',
      "audioTemplatepath":'drawing-tool_cpl_template_G3_12'
   },
   "ih_image_hotspot":{
      "html":"../../assets/modules/hmh.explib_hotspot/widgets/explib_hot_spot/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/ih_explore_cpl_template_G3_12.json",
      "mappingPath":"../Mapping/ih_explore_mapping_G3_12.json",
      "templateKG":"../cpl-config/ih_explore_cpl_template_GK_2.json",
      "mappingKG":"../Mapping/ih_explore_mapping_GK_2.json",
      "value":"ih-explore",
      "audioMappingpath":'ih_image_hotspot_mapping_audio_G3_12',
      "audioTemplatepath":'ih_image_hotspot_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/ih_image_hotspot/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/ih_image_hotspot\/index.html/
   },
   "ftq_main":{
      "html":"../../assets/modules/hmh.free_text_question/widgets/explib_ftq_fiq/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/ftq_cpl_template_G3_12.json",
      "mappingPath":"../Mapping/ftq_mapping_G3_12.json",
      "templateKG":"../cpl-config/ftq_cpl.json",
      "mappingKG":"../Mapping/ftq_mapping.json",
      "value":"ftq-main",
      "audioMappingpath":'ftq_main_mapping_audio_G3_12',
      "audioTemplatepath":'ftq_main_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/ftq_main/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/ftq_main\/index.html/
   },
   "line_matching":{
      "html":"../../assets/modules/hmh.line_matching/widgets/explib_line_matching/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/line_matching_cpl_template_G3_12.json",
      "mappingPath":"../Mapping/line_matching_mapping_G3_12.json",
      "templateKG":"../cpl-config/line_matching_cpl_template_GK_2.json",
      "mappingKG":"../Mapping/line_matching_mapping_GK_2.json",
      "value":"k2_line_matching",
      "audioMappingpath":'line_matching_mapping_audio_G3_12',
      "audioTemplatepath":'line_matching_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/line_matching/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/line_matching\/index.html/
   },
   "ftq_table":{
      "html":"../../assets/modules/hmh.free_text_question_table/widgets/explib_ftq_table/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/ftq_table_cpl_template_G3_12.json",
      "mappingPath":"../Mapping/ftq_table_mapping_G3_12.json",
      "templateKG":"../cpl-config/ftq_table_cpl.json",
      "mappingKG":"../Mapping/ftq_table_mapping.json",
      "value":"ftq-table",
      "audioMappingpath":'ftq_table_mapping_audio_G3_12',
      "audioTemplatepath":'ftq_table_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/ftq_table/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/ftq_table\/index.html/
   },
   "fiq_table":{
      "html":"../../assets/modules/hmh.fill_in_question_table/widgets/explib_fiq_table/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/fib_table_cpl_template_G3_12.json",
      "mappingPath":"../Mapping/fib_table_mapping_G3_12.json",
      "templateKG":"../cpl-config/fib_table_cpl_template.json",
      "mappingKG":"../Mapping/fib_table_mapping.json",
      "value":"fib-table",
      "audioMappingpath":'fiq_table_mapping_audio_G3_12',
      "audioTemplatepath":'fiq_table_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/fiq_table/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/fiq_table\/index.html/
   },
   "ddd_table":{
      "html":"../../assets/modules/hmh.drag_drop_table/widgets/explib_drag_drop_table/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/ddd_table_cpl_template_G3_12.json",
      "mappingPath":"../Mapping/ddd_table_mapping_G3_12.json",
      "templateKG":"../cpl-config/ddd_table_cpl_template.json",
      "mappingKG":"../Mapping/ddd_table_mapping.json",
      "value":"drag-and-drop-table",
      "audioMappingpath":'ddd_table_mapping_audio_G3_12',
      "audioTemplatepath":'ddd_table_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/ddd_table/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/ddd_table\/index.html/
   },
   "ddd_background":{
      "html":"../../assets/modules/hmh.drag_drop_background/widgets/explib_drag_drop_background/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/ddd_bg_cpl_template_G3_12.json",
      "mappingPath":"../Mapping/ddd_bg_mapping_G3_12.json",
      "templateKG":"../cpl-config/ddd_bg_cpl_template_GK_2.json",
      "mappingKG":"../Mapping/ddd_bg_mapping_GK_2.json",
      "value":"drag-and-drop-bg",
      "audioMappingpath":'ddd_background_mapping_audio_G3_12',
      "audioTemplatepath":'ddd_background_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/ddd_background/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/ddd_background\/index.html/
   },
   "mdq_single":{
      "html":"../../assets/modules/hmh.drop_down/widgets/explib_drop_down/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/mdq_simple_cpl_template_G3_12.json",
      "mappingPath":"../Mapping/mdq_simple_mapping_G3_12.json",
      "templateKG":"../cpl-config/mdq_simple_cpl_template.json",
      "mappingKG":"../Mapping/mdq_simple_mapping.json",
      "value":"exp-dropdown",
      "audioMappingpath":'mdq_single_mapping_audio_G3_12',
      "audioTemplatepath":'mdq_single_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/mdq_single/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/mdq_single\/index.html/
   },
   "tr_tap_to_revel_main":{
      "html":"../../assets/modules/hmh.tap_to_reveal/widgets/explib_tap_to_reveal/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/tr_main_cpl_template_G3_12.json",
      "mappingPath":"../Mapping/tr_main_mapping_G3_12.json",
      "templateKG":"../cpl-config/tr_main_cpl_template.json",
      "mappingKG":"../Mapping/tr_main_mapping.json",
      "value":"tap-to-reveal",
      "audioMappingpath":'tr_tap_to_revel_main_image_mapping_audio_G3_12',
      "audioTemplatepath":'tr_tap_to_revel_main_image_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/tr_tap_to_revel_main/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/tr_tap_to_revel_main\/index.html/
   },
   "tr_image_update_tap":{
      "html":"../../assets/modules/hmh.tap_to_reveal/widgets/explib_tap_to_reveal/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/tr_image_cpl_template_G3_12.json",
      "mappingPath":"../Mapping/tr_image_mapping_G3_12.json",
      "templateKG":"../cpl-config/tr_image_cpl_template.json",
      "mappingKG":"../Mapping/tr_image_mapping.json",
      "value":"tap-to-reveal",
      "audioMappingpath":'tr_image_update_tap_mapping_audio_G3_12',
      "audioTemplatepath":'tr_image_update_tap_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/tr_image_update_tap/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/tr_image_update_tap\/index.html/
   },
   "video-gallery":{
      "html":"../../assets/modules/hmh.video/widgets/explib_video/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/vg_cpl_template_G3_12.json",
      "mappingPath":"../Mapping/vg_mapping_G3_12.json",
      "templateKG":"../cpl-config/vg_cpl_template.json",
      "mappingKG":"../Mapping/vg_mapping.json",
      "value":"video-gallery",
      "audioMappingpath":'ag_background_mapping_audio_G3_12',
      "audioTemplatepath":'ag_background_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/video-gallery/index.html",
      "existingPath": "../../assets/widgets/ngss-widgets/video-gallery/index.html"
   },
   "ag_background":{
      "html":"../../assets/modules/hmh.audio_gallery/widgets/explib_audio_gallery/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/ag_cpl_template_G3_12.json",
      "mappingPath":"../Mapping/ag_mapping_G3_12.json",
      "templateKG":"../cpl-config/ag_cpl_template.json",
      "mappingKG":"../Mapping/ag_mapping.json",
      "value":"audio-gallery",
      "audioMappingpath":'ag_background_mapping_audio_G3_12',
      "audioTemplatepath":'ag_background_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/ag_background/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/ag_background\/index.html/
   },
   "ddm_drag_drop_matching":{
      "html":"../../assets/modules/hmh.drag_drop_table/widgets/explib_drag_drop_table/index.html",
      "dataVersion":"",
      "templateKG":"../cpl-config/ddm_drag_drop_matching_cpl_template_GK_2.json",
      "mappingKG":"../Mapping/ddm_drag_drop_matching_mapping_GK_2.json",
      "value":"k2_ddm_table",
      "audioMappingpath":'ag_background_mapping_audio_G3_12',
      "audioTemplatepath":'ag_background_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/ddm_drag_drop_matching/index.html",
      "existingPath": "../../assets/widgets/ngss-widgets/ddm_drag_drop_matching/index.html",
   },
   "ddm_background":{
      "html":"../../assets/modules/hmh.drag_drop_background/widgets/explib_drag_drop_background/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/ddm_bg_cpl_template.json",
      "mappingPath":"../Mapping/ddm_bg_mapping.json",
	  "templateKG":"../cpl-config/ddm_bg_cpl_template_GK_2.json",
      "mappingKG":"../Mapping/ddm_bg_mapping_GK_2.json",
      "value":"drag-and-drop-img",
      "audioMappingpath":'ag_background_mapping_audio_G3_12',
      "audioTemplatepath":'ag_background_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/ddm_background/index.html",
      "existingPath": "../../assets/widgets/ngss-widgets/ddm_background/index.html"
   },
   "tap-to-reveal":{
      "html":"../../assets/modules/hmh.tap_to_reveal/widgets/explib_tap_to_reveal/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/tr_reveal_cpl_template.json",
      "mappingPath":"../Mapping/tr_reveal_mapping.json",
      "value":"tap-to-reveal",
      "audioMappingpath":'ag_background_mapping_audio_G3_12',
      "audioTemplatepath":'ag_background_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/tap-to-reveal/index.html",
      "existingPath": "../../assets/widgets/ngss-widgets/tap-to-reveal/index.html",
   },
   "tap-to-reveal-nested":{
      "html":"../../assets/modules/hmh.tap_to_reveal/widgets/explib_tap_to_reveal/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/tr_reveal_cpl_template.json",
      "mappingPath":"../Mapping/tr_reveal_mapping.json",
      "templateKG":"../cpl-config/tr_nested_cpl_template_GK_2.json",
      "mappingKG":"../Mapping/tr_nested_mapping_GK_2.json",
      "value":"tap-to-reveal-nest",
      "audioMappingpath":'ag_background_mapping_audio_G3_12',
      "audioTemplatepath":'ag_background_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/tap-to-reveal-nested/index.html",
      "existingPath": "../../assets/widgets/ngss-widgets/tap-to-reveal-nested/index.html"
   },
   "ddm_table":{
      "html":"../../assets/modules/hmh.drag_drop_table/widgets/explib_drag_drop_table/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/ddm_table_cpl_template_G3_12.json",
      "mappingPath":"../Mapping/ddm_table_mapping_G3_12.json",
      "templateKG":"../cpl-config/ddm_table_cpl_template.json",
      "mappingKG":"../Mapping/ddm_table_mapping.json",
      "value":"drag-and-drop-table",
      "audioMappingpath":'ddm_table_mapping_audio_G3_12',
      "audioTemplatepath":'ddm_table_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/ddm_table/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/ddm_table\/index.html/,
   },
   "mdq_paragraph":{
      "html":"../../assets/modules/hmh.drop_down/widgets/explib_drop_down/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/mdq_para_cpl_template_G3_12.json",
      "mappingPath":"../Mapping/mdq_para_mapping_G3_12.json",
      "templateKG":"../cpl-config/mdq_para_cpl_template.json",
      "mappingKG":"../Mapping/mdq_para_mapping.json",
      "value":"exp-dropdown",
      "audioMappingpath":'mdq_paragraph_mapping_audio_G3_12',
      "audioTemplatepath":'mdq_paragraph_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/mdq_paragraph/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/mdq_paragraph\/index.html/,
   },
   "fiq_fill_in_question":{
      "html":"../../assets/modules/hmh.fill_in_the_blank/widgets/explib_fill_in_the_blank/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/fiq_cpl_template_G3_12.json",
      "mappingPath":"../Mapping/fiq_mapping_G3_12.json",
      "templateKG":"../cpl-config/fiq_cpl_template.json",
      "mappingKG":"../Mapping/fiq_mapping.json",
      "value":"fiq-main",
      "audioMappingpath":'fiq_fill_in_question_mapping_audio_G3_12',
      "audioTemplatepath":'fiq_fill_in_question_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/fiq_fill_in_question/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/fiq_fill_in_question\/index.html/,
   },
   "ddd_drag_drop_dispenser":{
      "html":"../../assets/modules/hmh.drag_drop_table/widgets/explib_drag_drop_table/index.html",
      "dataVersion":"",
      "templateKG":"../cpl-config/ddd_main_cpl_template_GK_2.json",
      "mappingKG":"../Mapping/ddd_main_mapping_GK_2.json",
      "value":"drag-and-drop-table",
      "audioMappingpath":'ag_background_mapping_audio_G3_12',
      "audioTemplatepath":'ag_background_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/ddd_drag_drop_dispenser/index.html",
      "existingPath": "../../assets/widgets/ngss-widgets/ddd_drag_drop_dispenser/index.html"
   },
   "ddm_image":{
      "html":"../../assets/modules/hmh.drag_drop_background/widgets/explib_drag_drop_background/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/ddm_image_cpl_template_G3_12.json",
      "mappingPath":"../Mapping/ddm_image_mapping_G3_12.json",
      "templateKG":"../cpl-config/ddm_image_cpl_template.json",
      "mappingKG":"../Mapping/ddm_image_mapping.json",
      "value":"drag-and-drop-img",
      "audioMappingpath":'ddm_image_mapping_audio_G3_12',
      "audioTemplatepath":'ddm_image_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/ddm_image/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/ddm_image\/index.html/
   },
   "mdq_table":{
      "html":"../../assets/modules/hmh.drop_down/widgets/explib_drop_down/index.html",
      "dataVersion":"",
      "templateKG":"../cpl-config/mdq_table_cpl_template_GK_2.json",
      "mappingKG":"../Mapping/mdq_table_mapping_GK_2.json",
      "value":"exp-dropdown",
      "audioMappingpath":'ag_background_mapping_audio_G3_12',
      "audioTemplatepath":'ag_background_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/mdq_table/index.html",
      "existingPath": "../../assets/widgets/ngss-widgets/mdq_table/index.html"
   },
   "mcq_image":{
      "html":{"checkbox":"../../assets/modules/hmh.cpl_mcq_multi/widgets/cpl_mcq_multi/index.html","radio":"../../assets/modules/hmh.mcq_mrq/widgets/explib_mcq_mrq/index.html"},
      "dataVersion":{"checkbox":"","radio":""},
      "templateKG":{"checkbox":"../cpl-config/mcq_image_ms_cpl_template_GK_2.json","radio":"../cpl-config/mcq_image_ss_cpl_template_GK_2.json"},
      "mappingKG":{"checkbox":"../Mapping/mcq_image_ms_mapping_GK_2.json","radio":"../Mapping/mcq_image_ss_mapping_GK_2.json"},
      "templatePath":{"checkbox":"../cpl-config/mcq_image_ms_cpl_template_G3_12.json","radio":"../cpl-config/mcq_image_ss_cpl_template_G3_12.json"},
      "mappingPath":{"checkbox":"../Mapping/mcq_image_ms_mapping_G3_12.json","radio":"../Mapping/mcq_image_ss_mapping_G3_12.json"},
      "deciderProp":'inputType',
      "isControlled":true,
      "value":{"checkbox":"multi-select","radio":"single-select"},
      "audioMappingpath":{"checkbox":"mcq_ms_image_mapping_audio_G3_12","radio":"mcq_ss_image_mapping_audio_G3_12"},
      "audioTemplatepath":{"checkbox":"mcq_ms_image_cpl_template_G3_12","radio":"mcq_ss_image_cpl_template_G3_12"},
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/mcq_image/index.html",
      "existingPath": /\..\/..\/assets\/widgets\/ngss-widgets\/mcq_image\/index.html/
   },
   "mcq_text":{
      "html":{"checkbox":"../../assets/modules/hmh.cpl_mcq_multi/widgets/cpl_mcq_multi/index.html","radio":"../../assets/modules/hmh.mcq_mrq/widgets/explib_mcq_mrq/index.html"},
      "dataVersion":{"checkbox":"","radio":""},
      "templateKG":{"checkbox":"../cpl-config/mcq_text_ms_cpl_template_GK_2.json","radio":"../cpl-config/mcq_text_ss_cpl_template_GK_2.json"},
      "mappingKG":{"checkbox":"../Mapping/mcq_text_ms_mapping_GK_2.json","radio":"../Mapping/mcq_text_ss_mapping_GK_2.json"},
      "deciderProp":'inputType',
      "isControlled":true,
      "value":{"checkbox":"cpl-ms-mcq-text","radio":"ss-mcq-text"},
      "audioMappingpath":'ag_background_mapping_audio_G3_12',
      "audioTemplatepath":'ag_background_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/mcq_text/index.html",
      "existingPath": "../../assets/widgets/ngss-widgets/mcq_text/index.html"
   },
   "flip-cards":{
      "html":"../../assets/modules/hmh.flip_card/widgets/explib_flip_card/index.html",
      "dataVersion":"",
      "templatePath":"../cpl-config/flip_cpl_template.json",
      "mappingPath":"../Mapping/flip_mapping.json",
      "templateKG":"../cpl-config/flip_cpl_template_GK_2.json",
      "mappingKG":"../Mapping/flip_mapping_Gk_2.json",
      "value":"flip-card",
      "audioMappingpath":'ag_background_mapping_audio_G3_12',
      "audioTemplatepath":'ag_background_cpl_template_G3_12',
      "existingKGPath": "../../assets/widgets/ngss-widgets/k2/flip-cards/index.html",
      "existingPath": "../../assets/widgets/ngss-widgets/flip-cards/index.html"
   }
};

module.exports.matchingProps = matchingProps;